name: Update data

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install dependencies
        run: |
          install.packages(c("data.table", "dplyr", "googlesheets4",
          "stringr", "lubridate", "rsconnect", "pacman"))          
        shell: Rscript {0}
      - name: Update data
        run: |
          source("clean_data.R")          
        shell: Rscript {0}
      - name: Commit files
        run: |
          git config --local user.email "briannjuguna133@gmail.com"
          git config --local user.name "wagathu"
          git add --all
          git commit -m "add data"
          git push           
        continue-on-error: true 

          
