name: Deploy to shinyapps.io

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R environment
        uses: r-lib/actions/setup-r@v2

      - name: Install required R packages
        run: |
          Rscript -e "install.packages(c('rsconnect'))"

      - name: Authenticate and Deploy to shinyapps.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name = 'wagathu', token = '${{ secrets.TOKEN }}', secret = '${{ secrets.SECRET }}')"
          Rscript -e "rsconnect::deployApp(appFiles = c('app.R', 'data'), forceUpdate = TRUE)"
