name: Deploy to shinyapps.io

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t main .

      - name: Run Docker Container & Deploy App
        run: >
          docker run 
          -e SHINY_ACC_NAME='wagathu'
          -e TOKEN=${{ secrets.TOKEN }}
          -e SECRET=${{ secrets.SECRET }}
          -e APP_NAME='trial_app2'  # Ensure the correct app name is passed
          main
