name: Deploy to shinyapps.io

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'  # Use the latest stable R version

      - name: Install R dependencies
        run: |
          R -e 'options(repos = c(CRAN = "https://cloud.r-project.org")); install.packages(c("shiny", "rsconnect", "dplyr", 
          "highcharter", "data.table", "googledrive", "googlesheets4", "pacman"))'

      - name: Deploy to shinyapps.io
        env:
          SHINY_ACC_NAME: "wagathu"
          APP_NAME: "trial_app2"
          TOKEN: ${{ secrets.TOKEN }}
          SECRET: ${{ secrets.SECRET }}
      - name: Commit & Push Files
        run: |
          git config --local user.email "briannjuguna133@gmail.com"
          git config --local user.name "wagathu"
          git add --all
          git commit -m "Updated data from Google Sheets" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/wagathu/trial_app2.git
