name: Update Data

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_SHEETS_KEY: ${{ secrets.GOOGLE_SHEETS_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev pkg-config

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Install R Dependencies
        run: |
          R -e 'install.packages(c("pacman", "gargle", "httr", "googledrive", "data.table", "dplyr", "googlesheets4", "stringr", "lubridate"), repos="https://cloud.r-project.org")'

      - name: Run Data Update Script
        run: |
          Rscript clean_data.R
          
      - name: Commit & Push Files
        run: |
          git config --local user.email "briannjuguna133@gmail.com"
          git config --local user.name "wagathu"
          git add --all
          git commit -m "Updated data from Google Sheets" || echo "No changes to commit"
          git push
