name: Update data

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_SHEETS_KEY: ${{ secrets.GOOGLE_SHEETS_KEY }}  # Pass secret key

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        run: |
          R -e 'options(repos = c(CRAN = "https://cloud.r-project.org")); install.packages(c("pacman", "googledrive", "data.table", 
          "dplyr", "googlesheets4", "stringr", "lubridate")'
        shell: Rscript {0}  

      - name: Update data
        run: |
          source("clean_data.R")          
        shell: Rscript {0}

      - name: Commit files
        run: |
          git config --local user.email "briannjuguna133@gmail.com"
          git config --local user.name "wagathu"
          git add --all
          git commit -m "Updated data from Google Sheets"
          git push
